stages:
  - sync

sync_to_github:
  stage: sync
  before_script:
  - mkdir -p ~/.ssh
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
  script:
    - git remote add github git@github.com:polyglot-chameleon/stock-savvy.git
    - git push --mirror github
  only:
    - main
